/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dominio.Flete;
import dominio.Residuo;
import dominio.Transportista;
import dominio.Traslado;
import dominio.Usuario;
import fachada.INegocio;
import factory.FabricaFormularios;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulvazquez
 */
public class FrmSolicitudes extends javax.swing.JFrame {

    private INegocio negocio;
    private List<Traslado> listaTraslados;
    private FabricaFormularios fabrica;
    private List<Traslado> traslados;
    private Residuo residuoObtenido;
    public List<Usuario> transportistas;
    public List<Usuario> transportistasSeleccionados;

    /**
     * Creates new form FrmSolicitudes
     */
    public FrmSolicitudes(INegocio negocio) {
        initComponents();
        traslados = new ArrayList<>();
        this.negocio = negocio;
        transportistas = new ArrayList<>();
        transportistasSeleccionados = new ArrayList<>();
        this.listaTraslados = negocio.consultarTraslados();
        this.llenarTablaTraslados();
        this.fabrica = new FabricaFormularios();
        residuoObtenido = new Residuo();
    }

    public void llenarTablaTraslados() {
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblTrasladoNA.getModel();
        // Limpia tabla anterior
        modeloTabla.setRowCount(0);
        listaTraslados.forEach(traslado -> {
            traslados.add(traslado);
            Object[] fila = {
                traslado.getId(),
                traslado.getResiduo().get(0).getProductor().getNombre(),
                traslado.getFechaSolicitada()};
            modeloTabla.addRow(fila);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSolicitudesNoAtendidas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTrasladoNA = new javax.swing.JTable();
        btnSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtUnidadMedida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransportistas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTransportistasSeleccionados = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSolicitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSolicitudesNoAtendidas.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        lblSolicitudesNoAtendidas.setText("Solicitudes No Atendidas");
        getContentPane().add(lblSolicitudesNoAtendidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 62, -1, -1));

        tblTrasladoNA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Productor", "Fecha Solicitada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTrasladoNA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTrasladoNAMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTrasladoNA);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 142, -1, 162));

        btnSalir.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 22, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 386, -1, -1));

        txtCodigo.setEditable(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 384, 100, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 422, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Cantidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Unidad de medida");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        txtNombre.setEditable(false);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 420, 100, -1));

        txtCantidad.setEditable(false);
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 98, -1));

        txtUnidadMedida.setEditable(false);
        getContentPane().add(txtUnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 98, -1));

        tblTransportistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTransportistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransportistasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransportistas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 381, 177, 207));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Empresas Transportadoras");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 339, -1, -1));

        tblTransportistasSeleccionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTransportistasSeleccionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransportistasSeleccionadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblTransportistasSeleccionados);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 381, 186, 207));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Transportistas Seleccionadas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 339, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Residuo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 339, -1, -1));

        btnSolicitar.setText("Solicitar");
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSolicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 615, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        // TODO add your handling code here:

        if (transportistasSeleccionados == null) {

        } else if (residuoObtenido == null) {
        } else {
            float cantidadDivida = (residuoObtenido.getCantidad()) / (transportistasSeleccionados.size());
            for (int i = 0; i < transportistasSeleccionados.size(); i++) {
                negocio.agregarFlete(new Flete(residuoObtenido, transportistasSeleccionados.get(0), null, cantidadDivida));
            }

            JOptionPane.showMessageDialog(null, "Completada la solicitud");
            this.vaciarFormulario();
        }


    }//GEN-LAST:event_btnSolicitarActionPerformed

    public void vaciarFormulario() {
        this.txtCodigo.setText("");
        this.txtNombre.setText("");
        this.txtCantidad.setText("");
        this.txtUnidadMedida.setText("");

        this.buscarTransportistas();
        this.transportistasSeleccionados.clear();
        this.llenarTablaTransportistas();
        this.llenarTablaTransportistasSeleccionados();
    }

    public void llenarResiduo() {
        this.txtCodigo.setText(String.valueOf(residuoObtenido.getCodigo()));
        this.txtNombre.setText(String.valueOf(residuoObtenido.getNombre()));
        this.txtCantidad.setText(String.valueOf(residuoObtenido.getCantidad()));
        this.txtUnidadMedida.setText(String.valueOf(residuoObtenido.getUnidad()));

    }

    public void buscarTransportistas() {
        List<Usuario> usuarios = negocio.buscarUsuarios();
        System.out.println(usuarios.get(0));
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getTipo().equals("transportista")) {
                transportistas.add(usuarios.get(i));
            }
        }
    }

    public void llenarTablaTransportistas() {

        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblTransportistas.getModel();
        // Limpia tabla anterior
        modeloTabla.setRowCount(0);
        transportistas.forEach(transportista -> {

            Object[] fila = {
                transportista.getNombre()

            };
            modeloTabla.addRow(fila);
        });

    }

    public void llenarTablaTransportistasSeleccionados() {

        DefaultTableModel modeloTabla = (DefaultTableModel) this.tblTransportistasSeleccionados.getModel();
        // Limpia tabla anterior
        modeloTabla.setRowCount(0);
        transportistasSeleccionados.forEach(transportista -> {

            Object[] fila = {
                transportista.getNombre()

            };
            modeloTabla.addRow(fila);
        });

    }
    private void tblTrasladoNAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTrasladoNAMouseClicked
        // TODO add your handling code here:

        int filaTabla = this.tblTrasladoNA.getSelectedRow();

        FrmProductor formularioProductor = fabrica.crearFormularioProductor(traslados.get(filaTabla));
        formularioProductor.setVisible(true);
        formularioProductor.btnSeleccionar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                int filaTabla = formularioProductor.tblResiduos.getSelectedRow();

                residuoObtenido = formularioProductor.residuos.get(filaTabla);
                formularioProductor.dispose();
                llenarResiduo();
                buscarTransportistas();
                llenarTablaTransportistas();
            }

        });


    }//GEN-LAST:event_tblTrasladoNAMouseClicked

    private void tblTransportistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransportistasMouseClicked
        // TODO add your handling code here:
        int fila = this.tblTransportistas.getSelectedRow();
        Transportista transportistaSeleccionado = new Transportista();
        transportistaSeleccionado.setNombre((String) this.tblTransportistas.getValueAt(fila, 0));

        this.transportistasSeleccionados.add(transportistaSeleccionado);

        this.transportistas.remove(fila);

        this.llenarTablaTransportistas();
        this.llenarTablaTransportistasSeleccionados();
    }//GEN-LAST:event_tblTransportistasMouseClicked

    private void tblTransportistasSeleccionadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransportistasSeleccionadosMouseClicked
        // TODO add your handling code here:
        int fila = this.tblTransportistasSeleccionados.getSelectedRow();
        Transportista transportistaSeleccionado = new Transportista();
        transportistaSeleccionado.setNombre((String) this.tblTransportistasSeleccionados.getValueAt(fila, 0));

        this.transportistasSeleccionados.remove(fila);

        this.transportistas.add(transportistaSeleccionado);

        this.llenarTablaTransportistas();
        this.llenarTablaTransportistasSeleccionados();

    }//GEN-LAST:event_tblTransportistasSeleccionadosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSalir;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblSolicitudesNoAtendidas;
    private javax.swing.JTable tblTransportistas;
    private javax.swing.JTable tblTransportistasSeleccionados;
    private javax.swing.JTable tblTrasladoNA;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUnidadMedida;
    // End of variables declaration//GEN-END:variables
}
